[package]
name = "tiff"
version = "0.7.3"
authors = [
    "ccgn",
    "bvssvni <bvssvni@gmail.com>",
    "nwin",
    "TyOverby <ty@pre-alpha.com>",
    "HeroicKatora",
    "Calum",
    "CensoredUsername <cens.username@gmail.com>",
    "Robzz",
    "birktj"]
license = "MIT"
description = "TIFF decoding and encoding library in pure Rust"
repository = "https://github.com/image-rs/image-tiff"
exclude = ["tests/images/*", "tests/fuzz_images/*"]
edition = "2018"

[dependencies]
weezl = "0.1.0"
jpeg = { package = "jpeg-decoder", version = "0.2.4", default-features = false }
flate2 = "1.0.20"

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "lzw"
harness = false
